apiVersion: v1
kind: ConfigMap
metadata:
  name: my-func-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/helm-inflator
        network: true
        mounts:
        - type: bind
          src: 
          dst: /source

data:
  chart: bitnami/redis
  chart-repo: bitnami
  chart-repo-url: https://charts.bitnami.com/bitnami
  name: expected-args
  '--values': /source/values-redis.yaml
