apiVersion: v1
kind: ConfigMap
metadata:
  name: plug-config-fn2
  annotations:
    config.kubernetes.io/function: |
      container: 
        image: quay.io/aodinokov/templater-transformer
data:
  generated_secrets_flt: |
    kind: GrepFilter
    path: ['metadata', 'name']
    value: fn2-catalogue 
  fld_get: |
    kind: PathGetter
    path: %s
  entrypoint: |
    {{- $catalogue_x := KPipe .Items (list (KFilter .Data.generated_secrets_flt)) -}}
    {{- $catalogue := index $catalogue_x 0 -}}
    {{/* would like to have builtin/resource instead of using krm */}}
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: fn2-new-resource
      annotations:
        config.kubernetes.io/function: |
          container:
            image: quay.io/aodinokov/templater-transformer
    data:
      entrypoint: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: fn2-generatedcfg1
        data:
          fld1: {{ YValue (YPipe $catalogue (list (YFilter (printf .Data.fld_get "['data', 'param1']")))) }}
    ---
    apiVersion: builtin
    kind: PatchTransformer
    metadata:
      name: fn2-cfg1-patch
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: fn2-cfg1
      data:
      {{- if eq (YValue (YPipe $catalogue (list (YFilter (printf .Data.fld_get "['data', 'switch']"))))) "true" }}
        fld1: {{ YValue (YPipe $catalogue (list (YFilter (printf .Data.fld_get "['data', 'param1']")))) }}
      {{- else }}
        fld1: {{ YValue (YPipe $catalogue (list (YFilter (printf .Data.fld_get "['data', 'param2']")))) }}
      {{- end }}
    ---
    apiVersion: builtin
    kind: PatchTransformer
    metadata:
      name: fn2-cfg2-patch
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: fn2-cfg2
      data:
      {{- if eq (YValue (YPipe $catalogue (list (YFilter (printf .Data.fld_get "['data', 'switch']"))))) "false" }}
        fld1: {{ YValue (YPipe $catalogue (list (YFilter (printf .Data.fld_get "['data', 'param1']")))) }}
      {{- else }}
        fld1: {{ YValue (YPipe $catalogue (list (YFilter (printf .Data.fld_get "['data', 'param2']")))) }}
      {{- end }}

