apiVersion: v1
kind: ConfigMap
metadata:
  name: encrypt-config
data:
  cmd: encrypt
  cmd-extra-params-json-path-filter: '$[?(@.metadata.name=="keys")]'
  cmd-json-path-filter: '$[?(@.metadata.name=="SecretSubstitutions")]'
  unencrypted-regex: ^(kind|apiVersion|group|metadata)$
