# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

.PHONY: image

image:
	docker build -f Dockerfile . -t quay.io/aodinokov/podemul:isobuilder-ubuntu-v0.0.1
	#docker push quay.io/aodinokov/podemul:isobuilder-ubuntu-v0.0.1
