apiVersion: airshipit.org/v1alpha1
kind: Templater
metadata:
  name: fileserver-secret-template
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/aodinokov/templater-default:v0.0.1
values:
  url: x
  putUsername: x
  putPassword: x
template: |
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: put-server-creds
  stringData:
    putSever: {{ .url }}
    putUsername: {{ .putUsername }}
    putPassword: {{ .putPassword }}
