apiVersion: v1
kind: ConfigMap
metadata:
  name: ephemeral-initinfra-docs
  annotations:
    config.k8s.io/function: |
      container:
        image: quay.io/aodinokov/kustomize_build_dind:0.0.1 #gcr.io/kpt-functions/kustomize-build:stable
        user: "root"
        network:
          required: true
        envs:
        - KUSTOMIZE_PLUGIN_HOME=/cluster_root/manifests/type
    config.kubernetes.io/local-config: 'true'
data:
  path: /cluster_root/manifests/site/ephemeral_initinfra
  '--enable_alpha_plugins': '--enable_alpha_plugins'
  '--reorder': none
---
apiVersion: v1alpha1
kind: Grep
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/aodinokov/grep:v0.0.1
data:
  flt: |
    filters:
    - path:
      - kind
      value: Kptfile
      invertMatch: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ephemeral-initinfra-apply
  annotations:
    config.k8s.io/function: |
      container:
        image: quay.io/aodinokov/live:v0.0.1
        network:
          required: true
        envs:
        - KUBECONFIG=/cache/ephemeral_build_iso/adminConfig.yaml
    config.kubernetes.io/local-config: 'true'
data:
  cmd: apply
  inventoryObjectName: inventory-initinfra
  inventoryObjectNamespace: default
  inventoryId: a6ec3136-30a8-4bd5-a2d7-ccde1433f111
  reconcile-timeout: 15m
