resources:
- ../../../types/type1/catalogue

transformers:
- |-
  apiVersion: builtin
  kind: PatchTransformer
  metadata:
    name: patch-type1-catalogue
  patch: |
    apiVersion: airshipit.org/v1alpha1
    kind: VariableCatalogue
    metadata:
      name: type1-catalogue
    data:
      allFnParam1: valueOverridenBySite1
# this must always present (but order may vary)
- ../../../types/type1/catalogue/replacements
