# Site-level host catalogue.  This info feeds the Templater
# kustomize plugin config in the hostgenerator-m3 function.
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: host-catalogue
hosts:
  roles:
    controlplane:
    - name: node01
    worker: 
    - name: node03
    - name: node02
      ephemeral: true
  m3:
    node01:
      bootMode: UEFI
      macAddress: 52:54:00:b6:ed:31
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-target-1
      bmcUsername: root
      bmcPassword: r00tme
      ipAddresses:
        oam-ipv4: 10.23.25.102
        pxe-ipv4: 10.23.24.102
      macAddresses:
        oam: 52:54:00:9b:27:4c
        pxe: 52:54:00:b6:ed:31
      hardwareProfile: libvirt # defined in the hostgenerator-m3 function
    node02:
      bootMode: UEFI
      macAddress: 52:54:00:b6:ed:02
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-ephemeral
      bmcUsername: username
      bmcPassword: password
      ipAddresses:
        oam-ipv4: 10.23.25.101
        pxe-ipv4: 10.23.24.101
      macAddresses:
        oam: 52:54:00:9b:27:02
        pxe: 52:54:00:b6:ed:02
      hardwareProfile: libvirt
    node03:
      bootMode: UEFI
      macAddress: 52:54:00:b6:ed:23
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-worker-1
      bmcUsername: username
      bmcPassword: password
      ipAddresses:
        oam-ipv4: 10.23.25.103
        pxe-ipv4: 10.23.24.103
      macAddresses:
        oam: 52:54:00:9b:27:07
        pxe: 52:54:00:b6:ed:23
      hardwareProfile: libvirt
