resources:
- ../../../types/type1/configs

transformers:
- |-
  apiVersion: builtin
  kind: PatchTransformer
  metadata:
    name: patch-type1-catalogue
  patch: |
    apiVersion: airshipit.org/v1alpha1
    kind: VariableCatalogue
    metadata:
      name: type1-catalogue
    data:
      allFnParam1: valueOverridenBySite1
- ../../../types/type1/configs/transformers
