apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config2
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn-contrib/sops:v0.1.1
        envs:
        - SOPS_IMPORT_AGE
data:
  ignore-mac: true
