apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: openstack-endpoint-catalogue
  labels:
    airshipit.org/deploy-k8s: "false"
data:
  array:
  - field1: 1
    field2: 2
  - field1: 3
    field2: 4
