apiVersion: builtin
kind: PatchStrategicMergeTransformer
metadata:
  name: notImportantHere-delete
patches: |-
  apiVersion: airshipit.org/v1alpha1
  kind: VariableCatalogue
  metadata:
    name: versions-airshipctl
  $patch: delete
