apiVersion: v1
kind: ConfigMap
metadata:
  name: SecretSubstitutions
data:
  image: 'ENC[AES256_GCM,data:bE/Qzjs=,iv:gdJr0PlSR1srbySRQUBpr/W41qJ3L87G0Bjcp5ZM5+Y=,tag:ubHbnNdY9TgQCAFbxIze9A==,type:str]'
  tag: 'ENC[AES256_GCM,data:psZabnIh,iv:brcDfNyBOrtrmpQktpXVlUacCD7U3s0Co6Ev2fpp2qs=,tag:2h3XywRGSpZEa+cDBmubRg==,type:str]'
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cVcrQmNzcDZSdHNsVUhS
        eFk4aWhaS2VHazhCd1M3U0hURWVZMmpSWXlNCnppZW13eUI4Vk4wSDZiR2w1dTNi
        VUR0WThFdWxjT1dVMExaVGRGNllZaUkKLS0tIDFxSWxZaVUwYVJXZGlINWVDWmtO
        Y1NyMUU0VmhhYlVqREZuVzVaQy9YS1UKkScjqqGOaLSld9pwo2HDpLCUMbAXB3IX
        ox3K+l5v/RIsNKO+0p+a7n8ooSyyrt/zzdpbHFHHZCax+g5Fh+vWGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yt3tfqlfrwdwx0z0ynwplcr6qxcxfaqycuprpmy89nr83ltx74tqdpszlw
  azure_kv: []
  gcp_kms: []
  hc_vault: []
  kms: []
  lastmodified: '2021-06-16T17:14:28Z'
  mac: 'ENC[AES256_GCM,data:HeLsbPt0zbiQ52zVjO6gQuHaeypG7fMuMjdIQ4A8J6EytGa05ALyEo1MRWIBeXLNLNMMOwr5UXYjCk4A1IuLx6Jrt/opUWGAMPdpKKdIjmXMadMxvcOcIJ/XMX3prb1AB7/jc4eS7idNsa9AKAw1QmsSqxNqyStJr1huWTlXMgA=,iv:nmnaPGqll0gc4lqgPq26hTJmUneq/4u5vwkHck9uD6Y=,tag:nhPLsxrV0MB6o9vjmpgnaA==,type:str]'
  pgp: []
  unencrypted_regex: ^(kind|apiVersion|group|metadata)$
  version: 3.7.1
