# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: airshipit.org/v1alpha1
kind: PodEmulator
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/aodinokov/podemul:v0.0.1
spec:
  executables:
  - name: test
    cmdline: /tmp/x/script.sh
    env:
    - name: var
      value: testval
    volumeMounts:
    - name: default
      mountPath: /tmp/x
  volumes:
  - name: default
    secret:
      name: test-script
      defaultMode: 0777
---
apiVersion: v1
kind: Secret
metadata:
  name: test-script
type: Opaque
stringData:
  script.sh: |
    #!/bin/bash
    echo WORKS! $var >&2
