# fileserver for iso storage
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: fileserver-catalogue
values:
  url: http://10.23.24.1:8099
  putUsername: username
  putPassword: password
