apiVersion: airshipit.org/v1alpha1
kind: NodeBootstrap
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/aodinokov/redfish-default:v0.0.1
        network:
          required: true
spec:
  operations:
  - action: doRemoteDirect
  bmhRef:
    name: ephemeral
    namespace: default
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    config.kubernetes.io/path: baremetalhost_ephemeral.yaml
  name: ephemeral
  namespace: default
spec:
  bmc:
    address: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-ephemeral
    credentialsName: ephemeral-bmc-secret
  bootMACAddress: 52:54:00:b6:ed:02
  bootMode: UEFI
  firmware: null
  image:
    url: http://10.23.24.1:8099/ubuntu-focal.iso
  networkData:
    name: ephemeral-network-data
    namespace: default
  online: true
  rootDeviceHints:
    model: default
    vendor: default
---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: dXNlcm5hbWU=
kind: Secret
metadata:
  annotations:
    config.kubernetes.io/path: secret_ephemeral-bmc-secret.yaml
  name: ephemeral-bmc-secret
  namespace: default
type: Opaque
