resources:
- secret.yaml 

secretGenerator:
  - name: image-builder
    options:
      disableNameSuffixHash: true
    files:
    - files/build.sh
    - files/functions.sh
    - files/grub.conf
    - files/packages_install.sh
    - files/meta_data.json
    literals:
    - |
        isogen.yaml=builder:
          userDataFileName: /tmp/user-data/userData
          networkConfigFileName : /tmp/network-data/networkData
          outputMetadataFileName: output-metadata.yaml
        container:
          volume: ./cache/ephemeral_build_iso:/cache/ephemeral_build_iso
    - |
        build-iso.sh=#!/bin/bash
        BASEDIR="$(dirname "$(realpath "$0")")"
        CHROOT="${HOME}/LIVE_BOOT/chroot"
        mkdir -p "${CHROOT}"
        mkdir -p /cache/ephemeral_build_iso/
        chown $(stat -c "%u:%g" /cache) /cache/ephemeral_build_iso/
        cp /tmp/user-data/userData /cache/ephemeral_build_iso/
        cp /tmp/network-data/networkData /cache/ephemeral_build_iso/
        cp /tmp/admin-config/adminConfig /cache/ephemeral_build_iso/adminConfig.yaml
        "${BASEDIR}/build.sh" >&2
        curl "${PUT_SERVER}" -u "${PUT_USERNAME}":"${PUT_PASSWORD}" --upload-file /cache/ephemeral_build_iso/ubuntu-focal.iso >&2
        # emulating image-builder
        TARGET_IMAGE_URL="https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
        curl -sSLo /tmp/target-image.qcow2 ${TARGET_IMAGE_URL}
        md5sum /tmp/target-image.qcow2 | cut -d ' ' -f 1 > /tmp/target-image.qcow2.md5sum
        curl "${PUT_SERVER}" -u "${PUT_USERNAME}":"${PUT_PASSWORD}" --upload-file /tmp/target-image.qcow2 >&2
        curl "${PUT_SERVER}" -u "${PUT_USERNAME}":"${PUT_PASSWORD}" --upload-file /tmp/target-image.qcow2.md5sum >&2
  - name: ephemeral-admin-config
    options:
      disableNameSuffixHash: true
    literals:
    - adminConfig=empty

generators:
- ../functions/hostgenerator-ephemeral
- ../functions/fileserver

transformers:
- copyAdminConfig.yaml 
