apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config2
  annotations:
    config.k8s.io/function: |
      container:
        image: quay.io/aodinokov/sops:v0.0.3
        envs:
        - SOPS_IMPORT_PGP
data:
  ignore-mac: true
