apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.k8s.io/function: |
      container:
        image: quay.io/aodinokov/sops:v0.0.3
        envs:
        - SOPS_IMPORT_PGP
data:
  cmd: encrypt
  pgp: 'FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4'
  unencrypted-regex: '^(kind|apiVersion|group|metadata)$'

