apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: fileserver-secret-replacements
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/aodinokov/replacement-default:v0.0.2
replacements:
- source:
    objref:
      name: fileserver-catalogue
    fieldref: values
  target:
    objref:
      kind: Templater
      name: fileserver-secret-template
    fieldrefs: [values]

