apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: type1-fn1-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:latest
replacements:
- source:
    objref:
      kind: VariableCatalogue
      name: type1-catalogue
    fieldref: "{.crt}"
  target:
    objref:
      kind: VariableCatalogue
      name: fn1-catalogue
    fieldrefs: ["{.crt}"]
- source:
    objref:
      kind: VariableCatalogue
      name: type1-catalogue
    fieldref: "{.key}"
  target:
    objref:
      kind: VariableCatalogue
      name: fn1-catalogue
    fieldrefs: ["{.key}"]
